### ISSUE TITLE
make a script to delete old files from OpenAI

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/bidara-deep-chat#100]
https://platform.openai.com/docs/api-reference/files/delete

maybe we delete files if they haven't been used in a run in awhile.

might be nice to somehow tag files we create during testing, so they can be deleted, while files generated by actual users can be kept.

**Comment by jackitaliano** [comment]
Was just thinking about this because I've created a lot of files in the past few days from testing. I'll look into it.

**Comment by jackitaliano** [comment]
See [oait](github.com/jackitaliano/oait)

## Install
```
brew tap --custom-remote github.com/jackitaliano/homebrew-tap jackitaliano/homebrew-tap
brew install oait
```

## Use
- Delete files older than 7 days:
`oait files del -A -D 7`

Unsure of a way to tag files right now. As far as I'm aware, this isn't a feature of OpenAI's files.

**Comment by jackitaliano** [comment]
Can look to make a CI/CD script to call on this functionality periodically, but for now closing issue.
