### ISSUE TITLE
Make it easy for users to "install pwa app"

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/bidara-deep-chat#50]
I'm envisioning a button on the login screen to "add to home screen". Similar to visiting a website of a service that is also available as an app prompts you to "install or open in app". Go to `reddit.com` for an example of this.

From this post https://stackoverflow.com/questions/38826397/add-to-home-screen-functionality-using-javascript:

> According to the Best Practices section of this page: https://developer.chrome.com/multidevice/android/installtohomescreen#best-practices
> 
> Do not prompt the user to add your app to the homescreen. There is no way to detect if the app is running installed or not.
> It looks like other developers have suggested that you can simply prompt the user with instructions for how to add to the homescreen, rather than try and do it directly.
> 
> EDIT: Doing more digging, it seems that since chrome 42, google is introducing app install banners. See: https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android
> 
> Your web app will need to meet a bunch of requirements however, including running a [service worker](https://developers.google.com/web/fundamentals/primers/service-worker/), having your site as https, and having the user visit your site at least twice.

**Comment by jackitaliano** [comment]
It seems this would only work on chrome, and not at all on iOS. 

I'll continue looking into this, but as of right now it seems iOS doesn't (or won't) support this feature.

**Comment by bruffridge** [comment]
ok, closing for now.
