### ISSUE TITLE
When a thread run errors, it locks the thread.

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/bidara-deep-chat#57]
Got a 500 error on a thread run, and then when I submitted another message, it says "Can't add messages to a thread while a run is active". Maybe catch these errors and stop the run so the conversation on the thread can continue.

<img width="750" alt="image" src="https://github.com/nasa-petal/bidara-deep-chat/assets/1322063/b07f8906-d1c9-4f28-b45d-c61c82b6ef50">

**Comment by jackitaliano** [comment]
Can add in logic to stop thread run in `deepChat.onError` function to solve this. Will put this in right after vision/threads due to some changes in there.
