### ISSUE TITLE
can't switch threads on iOS (safari or chrome)

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/bidara-deep-chat#76]
Bug found on `main` and `vision-only`, which are the only branches I tested.

To reproduce:
- Go to the production site on iPhone or `vision-only` in iOS simulator. 
- Make 3 threads.
- Try switching between threads (nothing happens).

**Comment by jackitaliano** [comment]
Not sure how this didn't appear earlier... Unrelated to these changes, so leaving it out of this branch. Pushed fix to `threads-sync` where it is somewhat more related.
