### ISSUE TITLE
generated images do not appear in `vision-only`

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/bidara-deep-chat#78]
![image](https://github.com/nasa-petal/bidara-deep-chat/assets/1322063/4fe9ca17-3d9d-476d-8538-b656ccc81db8)

**Comment by jackitaliano** [comment]
This seems to have been a hallucination. It did not call the image generation function here. If it did, the image would have to be inserted as a separate chat message.

In any case, threads-sync branch (next thing to merge), has a "rework" on storing and displaying of files, including images.

I'll look into this, but I believe unrelated to these changes.
