### ISSUE TITLE
evaluate the new GPT-4 Turbo with Vision `gpt-4-turbo-2024-04-09` model

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/bidara-deep-chat#97]
They recommend this model for both text and vision so could be a replacement for `gpt-4-1106-preview` and `gpt-4-1106-vision-preview` that we are currently using for text and vision respectively.
https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4

**Comment by jackitaliano** [comment]
This does not appear to work yet. They've released the model, but have prevented  using it via assistants for now. Not sure when they'll put this into assistants, but I'll keep an eye on it.

https://platform.openai.com/docs/guides/vision
> Plese note that the [Assistants API](https://platform.openai.com/docs/api-reference/assistants) does not currently support image inputs.

**Comment by bruffridge** [comment]
> This does not appear to work yet. They've released the model, but have prevented using it via assistants for now. Not sure when they'll put this into assistants, but I'll keep an eye on it.
> 
> https://platform.openai.com/docs/guides/vision
> 
> > Plese note that the [Assistants API](https://platform.openai.com/docs/api-reference/assistants) does not currently support image inputs.

I no longer see this restriction in the vision docs, however this issue has been superseded #111, so closing.
