### ISSUE TITLE
evaluate upgrading to v2 of the Assistants API

### ISSUE THREAD

**Issue by bruffridge** [nasa-petal/bidara-deep-chat#98]
https://platform.openai.com/docs/assistants/whats-new

Migration guide v1 to v2.
https://platform.openai.com/docs/assistants/migration/agents

v2 is required to use the latest `gpt-4o` model

(no longer) waiting for deep-chat support.
https://github.com/OvidijusParsiunas/deep-chat/issues/190

**Comment by bruffridge** [comment]
v2 support added to `deep-chat-dev`

**Comment by jackitaliano** [comment]
I've implemented changes to update to v2 through `deep-chat` and our thread logic; however, I believe one issue remains with the `deep-chat` implementation. Files, images, etc. are not replaced by the content of the file in the respective message's annotations.

Issue: https://github.com/OvidijusParsiunas/deep-chat/issues/214

Other than that, it seems V2 should be good.
